<!DOCTYPE HTML>
<html lang=".es">
<head> 
<link href="estilos.css" rel="stylesheet" type="text/css">
<meta charset="utf-8">

<title> Ukiyo Shop </title>
</head>

<body background= "fondo.jpg">
<div align="right">
<a href= "iniciar sesion.html"><input type="submit" class="boto" value="INICIAR SESION"> </a>
 
<a href= "formulario BD.PHP"> <input type="submit" class="boto" value="REGISTRARSE"> </a>
<input type="submit" class="boton" value="CARRITO DE COMPRAS">
</div>
<center><h1><img src="ukiyo.png"></h1></center>
<br>
<br>
<br>
<br>
<br>
<nav>
<ul>
<center>
<input type="submit" class="bot" value="PRODUCTOS">
<input type="submit" class="bot" value="CATALOGO">
<input type="submit" class="bot" value="ASESORIAS">
<input type="submit" class="bot" value="CONSULTAR PUNTOS">
</center>

</ul>

</nav>
<font face= "Manga" size="6">
<center> <font color="white" size= "6"> 

<h1> <img src= "Bien.png"> </h1> </center>
<center> <table border="6" width="50%" height="50%" bgcolor= "orange" > </center>
<tr>
<center> <td>  Bienvenidos a Ukiyo Shop  En esta tienda encontraras merchandising, figuras, peluches, accesorios y articulos personalizados de anime, manga !!!  </td> </center>
</tr></table></font>

<font color="green" size="6">
<tr>
<center> <h1> <img src="art.png"> </h1> </center>
<center> <td> <img src= "Muneca.png" height= "90%" width= "15%"> <img src= "luffy.png" height= "90%" width= "15%"> <img src= "nar.jpg" height= "90%" width= "15%"> <img src= "ryuk.jpg" height= "90%" width= "15%"> </center> </td>

</tr>

<tr>
<center> <h1>  <img src= "buz.png"> </h1> </center>
<center> <td> <img src= "pikachu.jpg" height= "90%" width= "15%">  <img src= "cha.png" height= "90%" width= "15%"> <img src= "luff.jpg" height= "90%" width= "15%"> <img src= "totoro.jpg" height= "90%" width= "15%"> </center> </td>

</tr>

<tr>
<center> <h1>  <img src= "moch.png"> </h1> </center>
<center> <td> <img src= "attack.jpg" height= "90%" width= "15%">  <img src= "mochil.jpg" height= "90%" width= "15%"> <img src= "mochila.jpg" height= "90%" width= "15%"> <img src= "one piece.jpg" height= "90%" width= "15%"> </center> </td>

</tr>

<tr>
<center> <h1>  <img src= "pel.png"> </h1> </center>
<center> <td> <img src= "nn.png" height= "90%" width= "15%">  <img src= "charmander.jpg" height= "90%" width= "15%"> <img src= "inuyasha.jpg" height= "90%" width= "15%"> <img src= "peluche.png" height= "90%" width= "15%"> </center> </td>
REGISTRO DE USUARIOS 
<a href="Registro usuario.php"> Registro Usuarios  </a>

</tr>


</font>
</body>
</html>